let str = `++01 BENNY BENASSI - SATISFACTION 2009 (JOHNNY MAX REMIX) 128 Electro
++02. BODYHEAT - IF YOU WANNA PARTY 128 
03 BOOTY LUV - SAY IT (WARREN CLARKE VOCAL MIX) 128
++04 C&C MUSIC FACTORY - MAKE YOU SWEAT 2009 (AMIR NACHMIAS EDIT) 128
05 CARLOS RUSSO - MASSIVE JOY (THOMAS GOLD REMIX) 128
+06. CHRIS KAESER - THE RHYTHM OF THE BEAT (ORIGINAL MIX) 128
+07 CODEC SHIFT - MEAN MOTION (DANISM AFTERDARK MIX) 128 Pro&Restre
08 DADDY'S GROOVE FT. LITTLE MARK- SATISFACTION 128
09. DAVID VENDETTA - LOVE TO LOVE YOU BABY (BQ) 128.01
10. DEADMAU5 - DR FUNKENSTEIN (DJ ZYA REMIX) 128.01
11 DEADMAU5 - GHOSTS N STUFF (HARD INTRO VERSION MIX) 128.01 Electro
++12 DELIRIUM-SILENCE 2009 (LISSATT & VOLTAXX REMIX) 128`;

str = ' ' + str
    .replace('\n', '\n ')
    .trim()
    .replaceAll('\n', ' ')
    .replaceAll(/ {1}\+*[0-9]{1,2}\.{0,1} {1}/g, '\n');
let arr = str.split('\n').slice(2);

let idx = 1;
for (const s of arr) {
    console.log(idx.toString().padStart(2,'0') + ' ' + s);
    idx++;
}

module.exports = arr;